---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/shuffle: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: BACKEND_HOSTNAME
          image: ghcr.io/shuffle/shuffle-frontend:latest
          name: shuffle-frontend
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
      hostname: shuffle-frontend
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      nodePort: 30007
    - name: "443"
      port: 443
      targetPort: 443
      nodePort: 30008
  selector:
    io.kompose.service: frontend
# status:
#   loadBalancer: {}
