apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: shuffle
subjects:
- kind: ServiceAccount
  name: default
  namespace: shuffle
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io

