apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args: ["--verbosity=debug",
               "--dockerfile=/workspace/Dockerfile",
               "--context=dir:///workspace",
               "--insecure",
               "--destination=shuffle-registry:5000/shuffle/dhaval-repo:1.0"
               ] 
        volumeMounts:
        - name: kaniko-workspace
          mountPath: /workspace
      restartPolicy: Never
      volumes:
      - name: kaniko-workspace
        hostPath:
          path: /home/docker/kaniko